### ISSUE TITLE
Platform fail

### ISSUE THREAD

**Issue by ChZinke** [Smunfr/sse-platform#19]
https://github.com/Smunfr/sse-platform/blob/1c1696b2b093ce160de2fbe70304cd42e68ced33/main.py#L256

Moin, das erzeugt bei mir immer einen Fehlstart, weil ja die Plattform selbst keine Conifg hat (bisher). Also entweder config rein, oder sys raus :)...

**Comment by Smunfr** [comment]
platform hat config auf dev branch. Geht auf master im nächsten Release.
